version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/node:8.16
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "e5:da:fd:41:3b:c1:5b:88:82:b8:ab:0d:a3:20:93:91"
      - run:
          name: merge develop into dist
          command: |
            git config user.email "kota65535@gmail.com"
            git config user.name "Tomohiko Ozawa"
            git checkout -b dist
      - run:
          name: build
          command: |
            npm install
            npm run build
      - run:
          name: add lib folder to git
          command: |
            sed -i -e '/\/dist/d' .gitignore
      - run:
          name: commit & push
          command: |
            git add . --all
            git diff-index --quiet HEAD || git commit -m "committed by CI"
            git push -f origin dist
